name: Local CI

on:
  push:
    branches:    
      - master  
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  schedule:
    - cron:  '0 0 * * *'
      
jobs:
  tests-ubuntu:
    runs-on: ubuntu-latest
    env:
      MOZ_HEADLESS_WIDTH: 1920
      MOZ_HEADLESS_HEIGHT: 1080
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Unit Tests
      run: ./gradlew clean checkstyleMain checkstyleTest test --tests "tests.unit.*"
    - name: Web Tests
      run: ./gradlew clean test --tests "tests.e2e.web.*" -Dconfig="github.local.firefox" -Dcores=2
  tests-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Unit Tests
      run: ./gradlew clean checkstyleMain checkstyleTest test --tests "tests.unit.*"
    - name: Web Tests
      run: ./gradlew clean test --tests "tests.e2e.web.*" -Dconfig="github.local.chrome" -Dcores=2
    - name: Desktop Tests
      run: ./gradlew clean test --tests "tests.e2e.desktop.*" -Dconfig="morse.windows"
  tests-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Chrome
      run: ./scripts/setup-macos.sh
    - name: Unit Tests
      run: ./gradlew clean checkstyleMain checkstyleTest test --tests "tests.unit.*"
    - name: Web Tests
      run: ./gradlew clean test --tests "tests.e2e.web.*" -Dconfig="github.local.chrome" -Dcores=2
